[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",  # necessary to enable link-time optimization (LTO) of the C library
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",  # necessary to enable link-time optimization (LTO) of the C library
]
