baseURL: "/"
languageCode: "en-us"
title: "SplinterDB"
theme: "template"
outputs:
  home: [ "HTML", "REDIRECTS" ]
pygmentsCodefences: true
pygmentsStyle: "pygments"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: native
    tabWidth: 4
menu:
  docs:
  - name: Overview
    url: /docs/
    weight: 100
  - name: Architecture
    url: /docs/architecture/
    name: Demo
    url: /docs/demo/
  - name: Scope
    url: /docs/scope/
  - name: Update Images
    url: /docs/contributing/
params:
  twitter_url: "https://twitter.com/splinterdbnews"
  github_url: "https://github.com/vmware/splinterdb"
  slack_url: "https://splinterdb.slack.com"
  googlegroups_url: "https://groups.google.com/g/splinterdb"
  github_base_url: "https://github.com/vmware/splinterdb"
  use_advanced_docs: true
  docs_right_sidebar: true
  docs_search: false
  docs_search_index_name: index_name
  docs_search_api_key: api_key
  docs_versioning: true
  docs_latest: v0.40.0
  docs_versions:
    - v0.30.0
    - v0.40.0
mediaTypes:
  "text/netlify":
    delimiter: ""
outputFormats:
  REDIRECTS:
    mediaType: "text/netlify"
    baseName: "_redirects"