---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/busybox

inputs:
- name: repo

outputs:
- name: tags

params:
  compiler: ((compiler))

run:
  path: /bin/sh
  args: ['-euc', 'sed -e "s/^/$compiler-/" repo/.git/ref > tags/tags && cat tags/tags']
