---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task

inputs:
- name: run-env-source
  path: .

outputs:
- name: image

params:
  BUILD_ARG_base_image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu:20.04
  DOCKERFILE: Dockerfile.run-env

run:
  path: build
