# Copyright 2018-2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task

inputs:
- name: build-env-source
  path: .

outputs:
- name: image

params:
  BUILD_ARG_base_image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu:20.04
  BUILD_ARG_compiler: ((compiler))
  DOCKERFILE: Dockerfile.build-env

run:
  path: build
